AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamodb-sns-integration

  Sample SAM Template for dynamodb-sns-integration
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DynamoDBStreamsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ddbstreamsprocessor/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Environment:
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - s3:*
          - logs:*
          - dynamodb:*
          - sns:*
          Resource:
          - "*"


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  DynamoDBStreamsFunction:
    Description: "DynamoDB Streams Function ARN"
    Value: !GetAtt DynamoDBStreamsFunction.Arn
  DynamoDBStreamsFunctionIamRole:
    Description: "Implicit IAM Role created for DynamoDB Streams Function"
    Value: !GetAtt DynamoDBStreamsFunctionRole.Arn
