AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  EEKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: EEKeyPair
    Description: Event Engine Name of the EC2 KeyPair generated for the Team
  LatestAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
    Description: Latest AMI from windows
Resources:
  DevCloud9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: Cloud9 environment for developer
      # ImageId: t3.medium
      InstanceType: t3.medium
      Name: DevCloud9Instance
      # OwnerArn: String 
      # Repositories: 
        # - Repository
      # SubnetId: String
      # Tags: 
        # - Tag
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 10
      ExplicitAuthFlows:
      - ALLOW_CUSTOM_AUTH
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_USER_SRP_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      IdTokenValidity: 10
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 10
      UserPoolId:
        Ref: CognitoUserPool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 1
      UsernameAttributes:
      - email
      UserPoolName: Samvaad-Userpool
  
Outputs:
  CognitoUserPool:
    Description: User pool identifier
    Value: !Ref CognitoUserPool
  CognitoUserPoolClient:
    Description: User pool identifier
    Value: !Ref CognitoUserPoolClient