version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "notification-management"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x8xagjaukjim"
s3_prefix = "notification-management"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
