# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  UserManagement

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  getUserPref:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/user_pref_get.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 15
      Description: Get a User's preferences
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        
  setUserPref:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/user_pref_set.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 15
      Description: Get a User's preferences
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        
  listPrefs:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/list_prefs.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 15
      Description: Get a User's preferences
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole